#!/bin/bash
echo "Post install script is running now"
mkdir -p /usr/share/soundsift
cat > /usr/share/soundsift/requirements.txt <<'EOF'
certifi
charset-normalizer
commonmark
customtkinter
darkdetect
et_xmlfile
idna
mutagen
openpyxl
packaging
Pygments
python-dotenv
redis
requests
rich
sentry-sdk
spotify_dl
spotipy
urllib3
yt-dlp
EOF
chmod 644 /usr/share/soundsift/requirements.txt

echo "Copying .desktop to Desktop folder"
for userdir in /home/*; do
    if [ -d "$userdir/Desktop" ]; then
        cp /usr/share/applications/soundsift.desktop "$userdir/Desktop/"
        chown $(basename $userdir):$(basename $userdir) "$userdir/Desktop/soundsift.desktop"
    fi
done
