#!/bin/bash
echo "Post install script is running now"
pip install --ignore-installed --break-system-packages \
    certifi \
    charset-normalizer \
    ommonmark \
    customtkinter \
    darkdetect \
    et_xmlfile \
    idna \
    mutagen \
    openpyxl \
    packaging \
    Pygments \
    python-dotenv \
    redis \
    requests \
    rich \
    sentry-sdk \
    spotify_dl \
    spotipy \
    urllib3 \
    yt-dlp

echo "Copying .desktop to Desktop folder"
for userdir in /home/*; do
    if [ -d "$userdir/Desktop" ]; then
        cp /usr/share/applications/soundsift.desktop "$userdir/Desktop/"
        chown $(basename $userdir):$(basename $userdir) "$userdir/Desktop/soundsift.desktop"
    fi
done
