[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "soundsift"
dynamic = ["version"]

authors = [
  { name="sivefunc", email="sivefunc@tuta.io" },
]

description = "Soundsift GUI YT/Spotify downloader"
readme = {file = 'README.md', content-type='text/markdown', charset="UTF-8", variant="GFM"}
requires-python = ">=3.11"

dependencies = [
  "customtkinter",
  "openpyxl",
  "requests",
  "spotify_dl",
  "spotipy",
  "yt_dlp",
  "python-dotenv",
  "mutagen",
]

[project.optional-dependencies]
dev = [
]

keywords = ['linux', 'python3', 'youtube', 'spotify']

[tool.setuptools.dynamic]
version = {attr = "soundsift._version.__version__"}

[project.urls]
Homepage = "https://github.com/eternityready2/SoundSift-MP3-Converter-for-Linux"

[project.scripts]
soundsift = "soundsift.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
soundsift = ["*.py", "*.json", "*.toml", "*.ini", "*.csv"]
