#!/bin/bash
echo "Post install script is running now"
pip install "customtkinter>=5.2.2" "openpyxl>=3.1.5" "requests>=2.32.3" "spotify_dl>=8.9.0" "spotipy>=2.25.1" "yt_dlp>=2025.2.19" --break-system-packages
