#!/bin/bash
echo "Post install script is running now"
pip install --ignore-installed customtkinter openpyxl requests spotify_dl spotipy yt_dlp --break-system-packages

echo "Copying .desktop to Desktop folder"
for userdir in /home/*; do
    if [ -d "$userdir/Desktop" ]; then
        cp /usr/share/applications/soundsift.desktop "$userdir/Desktop/"
        chown $(basename $userdir):$(basename $userdir) "$userdir/soundsift.desktop"
    fi
done
